### PR TITLE
Added fr-FR language

### PR DESCRIPTION
**Pull request by DimitriDR**
Title.

By the way, thank you for make a contributing simple and clear. Even with basic knowledge, I was able to do it 😃

### CODE REVIEW

**Comment by DimitriDR** [comment]
Before, merging this one, please, merge #263 as I use "cancel" instead of "cancle".

**Comment by seriousm4x** [comment]
Hey, thanks for adding French! Looked good so far.

I've merged #263 into this pr and removed some whitespace chars. You could have just kept pushing to `DimitriDR:i18n-add-fr` and it would have been in the pull request here ;)

Thanks!

**Comment by DimitriDR** [comment]
Hey,

No problem. Actually, white spaces are not a bug, but a feature ^^
In French, white spaces are required before any punctuation, except comma. I'm rather sure no other language does that. That's maybe why you're confused, but It is needed for perfect localization. It is possible to add a new commit to readd white spaces again?

Thanks.

**Comment by seriousm4x** [comment]
Oh, I didn't know that, sorry. I've added it back.

**Pull request merged**
