### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by irish1986**
I am proposing to include dependabot to improve docker image and github action to keep up to date.

### CODE REVIEW

**Comment by seriousm4x** [comment]
Good idea. Haven't really used dependabot so far.

`package-ecosystem: "github-actions"` checks the deploy workflow file for updates I guess?
When would `package-ecosystem: "docker"` trigger?

Also it'd be nice to have npm and go dependencies checked as well.

**Comment by irish1986** [comment]
> When would `package-ecosystem: "docker"` trigger?

It would be trigger when `alpine:3` from the Dockerfile gets update on [DockerHub](https://hub.docker.com/layers/library/alpine/3/images/sha256-e2e16842c9b54d985bf1ef9242a313f36b856181f188de21313820e177002501?context=explore).  In this case, 24 days ago.

This allows to re-run pipeline when the upstream image gets updated.

**Comment by irish1986** [comment]
> Also it'd be nice to have npm and go dependencies checked as well.

I will be working on this later, I really like this project since I've been looking for something like that for a while.  I am leveraging my DevSecOps skill first (expect other PR from me :) )but I am planning at looking more into the codebase and others.

**Comment by seriousm4x** [comment]
It looked quite good until you reverted everything 😄
Are you still working on it and should I wait?

**Comment by irish1986** [comment]
> It looked quite good until you reverted everything 😄 Are you still working on it and should I wait?

So I was pulled on a few personnel and work related emergencies.  I am going to take a look at it next week and reorganize the entirety of my PR to include dependancies management, new docker workflow and a few extra things.

I really am sorry, life got in the way I would prefer to close this PR then continue without achieving fully my idea.  I'll be back.

**Pull request closed without merging**
